\context ChordNames
	\chords {
		\set chordChanges = ##t
		\set majorSevenSymbol = \markup { "maj7" }
		% intro
		a1 b1:m/a a1 b1:m/a
		a1 b1:m/a a1 b1:m/a
		a1 b1:m/a a1 b1:m/a

		% noche de paz...
		a1 b1:m/a cis1:m fis1:m
		e1 e1:7 a1 e2:m a2:6sus2
		d1:maj7 e1:/d cis1:m fis1:m
		d1 c1:dim7 a1 fis1:m
		e1 gis1:dim fis1:m d1:maj7/dis
		a1:/e e1
		a1 b1:m/a a1 b1:m/a

		% noche de paz...
		a1 b1:m/a cis1:m fis1:m
		e1 e1:7 a1 e2:m a2:6sus2
		d1:maj7 e1:/d cis1:m fis1:m
		d1 c1:dim7 a1 fis1:m
		e1 gis1:dim fis1:m d1:maj7/dis
		a1:/e e1
		a1 b1:m/a a1 b1:m/a

		% noche de paz...
		a1 b1:m/a cis1:m fis1:m
		e1 e1:7 a1 e2:m a2:6sus2
		d1:maj7 e1:/d cis1:m fis1:m
		d1 c1:dim7 a1 fis1:m
		e1 gis1:dim fis1:m d1:maj7/dis
		a1:/e e1
		a1 b1:m/a a1 b1:m/a
		a1
	}
